### ISSUE TITLE
`genbbsub` is different from FORTRAN code

### ISSUE THREAD

**Issue by Berrysoft** [BxCppDev/bxdecay0#21] opened 2021-08-29 14:16 UTC
I have only checked the code related to Nd150.

Possible patch:

``` patch
diff --git a/bxdecay0/genbbsub.cc b/bxdecay0/genbbsub.cc
index 9f1bf28..d09135f 100644
--- a/bxdecay0/genbbsub.cc
+++ b/bxdecay0/genbbsub.cc
@@ -172,7 +172,7 @@ namespace bxdecay0 {
                 event & event_,
                 const int i2bbs_,
                 const std::string & chnuclide_,
-                const int ilevel_,
+                int ilevel_,
                 const int modebb_,
                 const int istart_,
                 int & ier_,
@@ -1209,6 +1209,11 @@ namespace bxdecay0 {
           bb_params_.Zdbb = 62.;
           bb_params_.Adbb = 150.;
           bb_params_.EK   = 0.;
+          if (modebb_ == 20) {
+            ilevel_         = 0;
+            bb_params_.Qbb  = 2.085;
+            bb_params_.Zdbb = 64.;
+          }
           if (ilevel_ < 0 || ilevel_ > 5) {
             std::cerr << "[error] "
                       << "bxdecay0::genbbsub: "
@@ -1939,7 +1944,7 @@ namespace bxdecay0 {
           bool m_ok = false;
           if (!m_ok && bb_params_.itrans02 == 0
               && (m == 1 || m == 2 || m == 3 || m == 4 || m == 5 || m == 6 || m == 9 || m == 10 || m == 11 || m == 12
-                  || m == 13 || m == 14 || m == 15 || m == 17 || m == 18 || m == 19)) {
+                  || m == 13 || m == 14 || m == 15 || m == 17 || m == 18 || m == 19 || m == 20)) {
             m_ok = true;
           }
           if (!m_ok && bb_params_.itrans02 == 2
```

**Comment by fmauger** [comment] 2021-08-30 16:16
Dear @Berrysoft 

I cannot accept your patch as is because you are modifying a readonly function arguments on the fly. You were forced to remove the const to allow that and thus to change the signature of the function. This is a very bad practice, A readonly argument is... well... readonly. It means that the user must know in advance what he/she wants and does not expect his/her choice  to be changed under  the table if found unappropriate after some check. 

Even using a local copy of ilevel and changing its value would be
a bad idea IMHO. 

One never knows the possible side effects, for example if the requested value of the 'ilevel' parameter has been saved in a config file before it is changed then used by the code itself, this would make things hard to track and reproduce because the config file won't tell you this is basically an error that is *fixed in some way* by the code itself.
An error is an error. I prefer to detect it and throw an exception and let the user shout and  cry for a while then re-run with the good set of parameters ! :-)

I'll try to find the reason of this issue ASAP. Probably I've skipped some check(s) from the original fortran code (the C++ port is only partly automated and request some manual ops... arrrghhh). The "Quadruple beta decay" mode has been added recently and I guess I have badly implemented it in the existing C++ code already merged from different versions. 
My bad !

Anyway thanks for the report. I'm starting to work on it from your hints.

regards.

**Comment by Berrysoft** [comment] 2021-08-31 05:19
Well, I hesitated when modifying `ilevel_`, but finally kept the code because the FORTRAN code does that:

https://github.com/BxCppDev/bxdecay0/blob/2401869e326d6da1ee0613e9022ad6bf5c9e8968/resources/code/decay0/decay0_2020-04-20.for#L2112

The patch above is only a possible patch, which only fixes for Nd150. I don't suggest just applying the patch, but suggest you checking the C++ code again. It seems that there are many checks for 0nu4b and maybe other modes missing when porting.

**Comment by fmauger** [comment] 2021-08-31 07:32
Yes you are right. I have identified the missing stuff for the three 4beta emitters. I think I have a fix now. In principle  I'll commit today after some tests. 
And yes, the legacy fortran code was odd for this specific point ! It should return an error when modebb == 20 and  ilevel != 0 . 
Thanks again. I think we are close to a solution. Stay tuned!
Regards

**Closed as completed** 2021-08-31 20:03 UTC
